"""Rigol DG1022 control UI."""
import pyvisa
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(440, 200)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 311, 161))
        self.groupBox.setObjectName("groupBox")
        self.func_type = QtWidgets.QComboBox(self.groupBox)
        self.func_type.setGeometry(QtCore.QRect(20, 50, 51, 22))
        self.func_type.setEditable(False)
        self.func_type.setObjectName("func_type")
        self.func_type.addItem("")
        self.func_type.addItem("")
        self.func_type.addItem("")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 30, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(100, 30, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(210, 30, 81, 16))
        self.label_3.setObjectName("label_3")
        self.frequency = QtWidgets.QLineEdit(self.groupBox)
        self.frequency.setGeometry(QtCore.QRect(100, 50, 81, 20))
        self.frequency.setObjectName("frequency")
        self.amplitude = QtWidgets.QLineEdit(self.groupBox)
        self.amplitude.setGeometry(QtCore.QRect(210, 50, 81, 20))
        self.amplitude.setObjectName("amplitude")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 80, 291, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.sweep_radio = QtWidgets.QRadioButton(self.groupBox_2)
        self.sweep_radio.setGeometry(QtCore.QRect(10, 40, 82, 17))
        self.sweep_radio.setObjectName("sweep_radio")
        self.burst_radio = QtWidgets.QRadioButton(self.groupBox_2)
        self.burst_radio.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.burst_radio.setChecked(True)
        self.burst_radio.setObjectName("burst_radio")
        self.label_cycle_start = QtWidgets.QLabel(self.groupBox_2)
        self.label_cycle_start.setGeometry(QtCore.QRect(100, 20, 71, 16))
        self.label_cycle_start.setObjectName("label_cycle_start")
        self.label_period_stop = QtWidgets.QLabel(self.groupBox_2)
        self.label_period_stop.setGeometry(QtCore.QRect(200, 20, 71, 16))
        self.label_period_stop.setObjectName("label_period_stop")
        self.cycle_start = QtWidgets.QLineEdit(self.groupBox_2)
        self.cycle_start.setGeometry(QtCore.QRect(100, 40, 71, 20))
        self.cycle_start.setObjectName("cycle_start")
        self.period_stop = QtWidgets.QLineEdit(self.groupBox_2)
        self.period_stop.setGeometry(QtCore.QRect(200, 40, 71, 20))
        self.period_stop.setObjectName("period_stop")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(340, 10, 91, 81))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton.setGeometry(QtCore.QRect(10, 20, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 50, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(350, 150, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 440, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Rigol DG1022"))
        self.groupBox.setTitle(_translate("MainWindow", "Configuración"))
        self.func_type.setCurrentText(_translate("MainWindow", "Sin"))
        self.func_type.setItemText(0, _translate("MainWindow", "Sin"))
        self.func_type.setItemText(1, _translate("MainWindow", "Pulse"))
        self.func_type.setItemText(2, _translate("MainWindow", "Arb"))
        self.label.setText(_translate("MainWindow", "Tipo"))
        self.label_2.setText(_translate("MainWindow", "Frecuencia [GHz]"))
        self.label_3.setText(_translate("MainWindow", "Amplitud [mV]"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Modo"))
        self.sweep_radio.setText(_translate("MainWindow", "Sweep"))
        self.burst_radio.setText(_translate("MainWindow", "Burst"))
        self.label_cycle_start.setText(_translate("MainWindow", "Ciclos"))
        self.label_period_stop.setText(_translate("MainWindow", "Período"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Guardar"))
        self.pushButton.setText(_translate("MainWindow", "Usuario"))
        self.pushButton_2.setText(_translate("MainWindow", "Volátil"))
        self.pushButton_3.setText(_translate("MainWindow", "Aplicar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
